### ISSUE TITLE
次の制御点までのカーブを直線にする

### ISSUE THREAD

**Issue by nea-c** [mimaraka/aviutl-plugin-curve_editor#15]
右側のハンドルをダブルクリックなど

左側でやると前の制御点までを直線にできても面白そう

**Comment by mimaraka** [comment]
https://user-images.githubusercontent.com/106879397/207261782-286a317d-f5a5-4cf6-82e9-0e9cf71b4266.mp4

こんな感じのもので大丈夫ですか？

**Comment by nea-c** [comment]
強い...

**Comment by nea-c** [comment]
これってハンドル戻せたりしますか？

**Comment by mimaraka** [comment]
ハンドルを制御点の真上に移動させているので重なっている所をドラッグしてやれば戻すことができます。

**Comment by nea-c** [comment]
なるほど！めっちゃ良いです！ありがとうございます！ 🙇
