### ISSUE TITLE
「次の制御点までのカーブを直線にする」の機能について

### ISSUE THREAD

**Issue by nea-c** [mimaraka/aviutl-plugin-curve_editor#16]
### まずは、実装ありがとうございます。

この機能に関して追加してもらいたいと考えている機能があります。

* 制御点の上にハンドルがある場合、Ctrlなどを同時に押すとハンドル(もしくは制御点)をドラッグ可能になるような仕組みの追加

です。

現在は制御点の上にハンドルが移動するため、制御点を移動したい場合一度ハンドルを横にどける必要があります。
この手間を良しと考えるのもありですが、直線状態のプレビューを見ながら調整できないのがデメリットと感じたため要望させていただきました。

**Comment by mimaraka** [comment]
そのような機能の追加は確かに必要だと考えていますが、残念ながらCtrl,Shift,Altキーなどを押しながらの編集にはすでに別のモードが割り当てられているため、他の操作で動かせるようにする必要があります。

**Comment by nea-c** [comment]
なるほど...

**Comment by mimaraka** [comment]
すみません…
Ctrlキーが割り当てられているのはハンドルの操作のみで、制御点の操作とは関係なかったので普通にCtrlキーで実装できました…。
下の動画のような動作で大丈夫そうですか？
(制御点を移動させているときはCtrlキーを押しています。)

https://user-images.githubusercontent.com/106879397/209688852-2a4b4b74-2073-4e2e-a410-47a782f67805.mp4

**Comment by nea-c** [comment]
！！！！！
最強だ...

**Comment by mimaraka** [comment]
v1.0.5にて実装いたしました！
(オプションになっているので、`設定`→`ハンドルをダブルクリックしたときにカーブを直線にする(ベジェ(複数))`にチェックを入れて有効化してください)
