### ISSUE TITLE
IDを入力 のダイアログの表記に誤り

### ISSUE THREAD

**Issue by nazonoSAUNA** [mimaraka/aviutl-plugin-curve_editor#17]
https://github.com/mimaraka/aviutl-plugin-curve_editor/blob/master/curve_editor/curve_editor.rc

0～1023の範囲のIDを入力してください
↓
1～1024の範囲のIDを入力してください
と思われます

**Comment by mimaraka** [comment]
前のバージョンでのIDの範囲を0~1023としており、表記の修正を忘れていました。
時期バージョンで修正します。
