### ISSUE TITLE
ドラッグ&ドロップができない場合がある

### ISSUE THREAD

**Issue by mimaraka** [mimaraka/aviutl-plugin-curve_editor#18]
らしいです。
こちら側でバグの再現ができないので全く分かりません。
このバグが起こっている方がいましたら環境・具体的な挙動等教えてくださると嬉しいです。

**Comment by kiyotaror** [comment]
初めまして、このバグが起こっていた人です
curve_editor.aufをexedit.aufのあるフォルダに入れていたのを、pluginsフォルダに移したところD&Dが可能となりました
curve_editor.aufをexedit.aufと同一のフォルダに入れていると再現できるかもしれません、よろしくお願いします。
ちなみにその時の挙動は「トラックバーの移動方法選択ボタンにD&Dしても青い網掛けの表示が出ず、何も起こらない」です。

**Comment by mimaraka** [comment]
バグ報告ありがとうございます…！
原因が判明しましたので、v1.0.3にて修正させていただきました。
詳細な原因・症状の説明本当に助かります。
