### ISSUE TITLE
表示状態切替後に拡張編集TLor設定ダイアログを右クリックすると例外が出るor落ちる

### ISSUE THREAD

**Issue by AyaExpTech** [mimaraka/aviutl-plugin-curve_editor#19]
ver1.0.3導入下でCurveEditorウィンドウの表示状態を切り替えたあとに拡張編集のタイムラインかオブジェクトの設定ダイアログを右クリックすることで例外が出る、もしくはAviUtlが強制終了します。

[初観測時のデバッグログ](https://github.com/mimaraka/aviutl-plugin-curve_editor/files/10298791/2022-12-24_23-18-17-706_32548.txt)

- 誘発条件は「CurveEditor設定ダイアログの表示状態を切り替えてから拡張編集ウィンドウかオブジェクト設定ダイアログを右クリック」のようです。
- 再生プレビューウィンドウの右クリックでは例外は発生しませんでした。
- ver1.0.2で同様の操作をしても例外などは発生しませんでした。

**Comment by mimaraka** [comment]
バグ報告ありがとうございます。
v1.0.4にて修正させていただきました。
