### ISSUE TITLE
バックアップファイルにベジエ(複数)のデータを残してほしい

### ISSUE THREAD

**Issue by yak9909** [mimaraka/aviutl-plugin-curve_editor#21]
タイトルの通りです、出来ればお願いします

**Comment by mimaraka** [comment]
現在の保存方式ではバックアップファイルにデータを格納できないため、タイムラインオブジェクトにデータを格納するなどといった方式をとらないと保存は難しそうです。
今後のアップデートでそのような機能の追加を検討しますのでしばらくお待ちいただければ幸いです。

代わりといっては何ですが、保存済みのプロジェクトを一定時間ごとに自動で保存するプラグインを作ってみたので良ければお使いください。
https://github.com/mimaraka/aviutl-plugin-auto_save
こちらはプロジェクトを保存するためCurve Editorのデータも保持されます。

**Comment by yak9909** [comment]
分かりました、ありがとうございます

そちらのプラグインを使わせて頂きます。わざわざありがとうございます！
