### ISSUE TITLE
保存する度にプロジェクトファイルのサイズが大きくなる

### ISSUE THREAD

**Issue by hebiiro** [mimaraka/aviutl-plugin-curve_editor#43]
## バグの説明

プロジェクトファイルを保存する度にファイルサイズが増加してしまいます。

## バグの再現方法

1. curve_editor-v2.0-alpha2.2.1を導入します。
2. カーブエディタでいくつかカーブを作成します。
3. プロジェクトファイルを保存します。
4. 何も編集せずに再びプロジェクトファイルを別名で保存します。
5. 4を何度か繰り返します。
6. 繰り返す度にプロジェクトファイルのファイルサイズがどんどん大きくなります。

## 期待していた動作

プロジェクトに変更を加えていない場合は、ファイルサイズは変化しない。

## スクリーンショット
![Curve Editor でファイルサイズが増加する](https://github.com/user-attachments/assets/3bdc8129-818e-4f04-bb1f-c399b13eec3e)
ce1.aup、ce2.aup、ce3.aupの順に連続して別名保存しています。
別名保存しただけでファイルサイズが332バイトずつ増加していっています。

## 環境(以下の欄を全て記述してください):
 - OS: Win11 Home 64bit 23H2 (10.0.22631)
 - バージョン(AviUtl): 1.10
 - バージョン(拡張編集): 0.92
 - バージョン(Curve Editor): curve_editor-v2.0-alpha2.2.1

## 補足
https://github.com/mimaraka/aviutl-plugin-curve_editor/blob/ec93d32ab851e7c72ba0aa28947599e3092fce36/curve_editor/filter_project_save.cpp#L9-L27
ここで文字列ストリームを使いまわしているのが原因だと思います。
下記のように書き込んだら文字列ストリームを開放するようにしたらどうでしょうか。
```
namespace cved {
	BOOL filter_project_save(AviUtl::FilterPlugin*, AviUtl::EditHandle*, void* data, int32_t* size) {
		//// [change] ossをスマートポインタに変更
		//// static std::ostringstream oss;
		static std::unique_ptr<std::ostringstream> oss_ptr;

		// まずサイズの取得のためにdataがNULLで呼び出される
		// ここでカーブのデータを作成しておく
		if (!data) {
			//// [add] ここでスマートポインタを初期化
			oss_ptr.reset(std::make_unique<std::ostringstream>());

			//// [add] スマートポインタからossを取得
			std::ostringstream& oss = *oss_ptr;

			cereal::BinaryOutputArchive archive(oss);
			archive(global::editor);
			*size = static_cast<int32_t>(oss.str().size());
		}
		// dataにデータをコピーする
		//// [change] スマートポインタが有効かチェックするように変更
		//// else {
		else if (oss_ptr) {
			//// [add] スマートポインタからossを取得
			std::ostringstream& oss = *oss_ptr;

			memcpy(data, oss.str().data(), oss.str().size());

			//// [add] ここでスマートポインタを開放
			oss_ptr.reset();
		}

		return TRUE;
	}
}
```

**Comment by hebiiro** [comment]
調べてみたら`std::ostringstream`をクリアする方法があるようなので、これを`memcpy()`のあとに追加するだけの方が簡単かもです。

https://www.paveway.info/entry/2018/12/18/cpp_stringstream_clear
> std::stringstream ss;
> 
> // バッファをクリアします。
> ss.str("");
> 
> // 状態をクリアします。
> ss.clear(std::stringstream::goodbit);

**Comment by mimaraka** [comment]
該当部分を修正いたしました
修正コードまで提案していただきありがとうございます…！
